"""update_organizations_and_add_audit_logs

Revision ID: 634049619754
Revises: 4850ba42b909
Create Date: 2026-09-12 00:50:51.003352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634049619754'
down_revision: Union[str, None] = '4850ba42b909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('code', sa.String(length=50), server_default='GEO-01', nullable=False))
    op.add_column('organizations', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), server_default='India', nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('max_admins', sa.Integer(), server_default='1', nullable=False))
    op.add_column('organizations', sa.Column('max_employees', sa.Integer(), server_default='50', nullable=False))
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_column('organizations', 'max_employees')
    op.drop_column('organizations', 'max_admins')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line2')
    op.drop_column('organizations', 'address_line1')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'code')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
